---
title: "R Notebook"
output: html_notebook
---


```{r}
library(MASS)
#this will be different for each user so might need to reformat to test/run
data = read.csv("~/Desktop/github/Stat337FP/breast-cancer.txt")
as.integer(data$X30.34)
data[data$left_low == '?',]$left_low = NA
data[data$no == '?',]$no = NA
colnames(data) = c(
  "reoccurance",
  "age",
  "meno",
  "tmsize",
  "invnodes",
  "nodecaps",
  "maldeg",
  "breast",
  "quad",
  "irradiat"
)

str(data)
```
```{r}
#chisq of reoccurance and categorical variables 
#test of independence H0 is that they are INdependent
#1
tbl1 = table(data$reoccurance, data$meno)
chisq.test(tbl1)

#2
#removes the first column of the table bc its values are 0
tbl2.2 = table(data$reoccurance, data$nodecaps)
tbl2 = tbl2.2[,-1]
chisq.test(tbl2)

#3
tbl3 = table(data$reoccurance, data$maldeg)
chisq.test(tbl3)

#4
tbl4 = table(data$reoccurance, data$breast)
chisq.test(tbl4)

#5
#removes the first column of the table bc its values are 0
tbl5.1 = table(data$reoccurance, data$quad)
tbl5 = tbl5.1[,-1]
chisq.test(tbl5)

#6
tbl6 = table(data$reoccurance, data$irradiat)
chisq.test(tbl6)

lr = glm(reoccurance ~., data = data, family = binomial(logit))
summary(lr)
```
Warning is because of small cell values so we can ignore it

```{r}
#t test of quad
quad = table(data['quad'])
t.test(cat)

#t sample t test of degree of mal to reoccurance
rec = table(data['reoccurance'])
t.test(rec)

lr = table(data['nodecaps'])
t.test(lr)

t.test(rec,lr)

lr = glm(reoccurance ~., data = data, family = binomial(logit))
summary(lr)
```




